# Site settings
title: Technical Dev Blog
email: arthur@maltson.com
description: > # this means to ignore newlines until "baseurl:"
  Technical development blog of Arthur Maltson. Covers many topics from Java 
  to Ruby to DevOps.

logo: /assets/images/jekyll.png
cover: /assets/images/code.jpg

name: Arthur Maltson
author: Arthur Maltson
author_image: /assets/images/author.jpg

paginate: 5

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devblog.maltson.com" # the base hostname & protocol for your site
twitter_username: amaltson
github_username:  amaltson

# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/amaltson
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/amaltson
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
