# Site settings
title: Random (Tech) Thoughts
email: arthur@maltson.com
description: > # this means to ignore newlines until "baseurl:"
  Personal, mostly non-technical blog of Arthur Maltson. I'll be posting
  random thoughts about tech, politics, science, culture, and so forth, here.

logo: /assets/images/jekyll.png
cover: /assets/images/andromeda.jpg

name: Arthur Maltson
author: Arthur Maltson
author_image: /assets/images/author.jpg

paginate: 5

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.maltson.com" # the base hostname & protocol for your site
twitter_username: amaltson
github_username:  amaltson

# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/amaltson
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/amaltson
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
